"""fixed

Revision ID: 408bc7b267a6
Revises: 02ec7599e0d9
Create Date: 2025-07-31 22:39:30.403869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '408bc7b267a6'
down_revision: Union[str, Sequence[str], None] = '02ec7599e0d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'payments', ['uuid'])
    op.create_unique_constraint(None, 'subscriptions', ['uuid'])
    op.create_unique_constraint(None, 'users', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_constraint(None, 'payments', type_='unique')
    # ### end Alembic commands ###
