"""add_subscription_relation

Revision ID: d8a28c63ccd5
Revises: 78c74a93851a
Create Date: 2025-07-31 18:55:20.024066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a28c63ccd5'
down_revision: Union[str, Sequence[str], None] = '78c74a93851a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'subscriptions', ['subscription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'subscription_id')
    # ### end Alembic commands ###
